services:
  laravel:
    build:
      context: .
      args:
        - USER_ID=${USER_ID:-1000}
        - GROUP_ID=${GROUP_ID:-1000}
    ports:
      - 6001:6001
    volumes:
      - .:/var/www
      - ./supervisord.conf:/etc/supervisor.conf
    networks:
      - discord_app
  nginx:
    image: nginx:stable
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./default.conf.template:/etc/nginx/templates/default.conf.template:ro
    networks:
      - discord_app
  mysql:
    image: mysql:8.4.0
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - 'mysql-data:/var/lib/mysql'
    networks:
      - discord_app

networks:
  discord_app:

volumes:
  mysql-data:
